# netlify.toml
[build]
  base = "docs"
  command = "jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.2.2"
  JEKYLL_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"