title: Eleda's Adventures
description: Venture through my website and discover a vague semblance of knowledge
remote_theme: jekyll/minima
url: "https://your-netlify-url.netlify.app" # Change this to your Netlify URL
baseurl: ""

minima:
  skin: dark

author:
  name: "Eleda of the Seventy-Seven"
  email: "adeleelda04@gmail.com"

header_pages:
  - about.md
  - discworld.md
  - book_thoughts.md
  - vocab_list.md

plugins:
  - jekyll-feed
  - jekyll-remote-theme

feed:
  path: feed.xml