title: Eleda's Adventures
description: Venture through my website and discover a vague semblance of knowledge
remote_theme: jekyll/minima
url: "eleda77.github.io" 


minima:
  skin: dark

author:
  name: "Eleda Yellek"
  email: "adeleelda04@gmail.com"

header_pages:
  - about.md
  - discworld.md
  - book_thoughts.md
  - vocab_list.md

plugins:
  - jekyll-feed

feed:
  path: feed.xml